language: csharp

matrix:
  include:
    - dotnet: 1.0.3
      mono: none
      dist: trusty
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp1.1
    - dotnet: 1.0.3
      mono: none
      dist: trusty
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.1
#    - mono: 4.8.1
#      env: CONFIGURATION=Debug FRAMEWORK=net452
#    - mono: 4.8.1
#      env: CONFIGURATION=Release FRAMEWORK=net452

before_script:
  - dotnet --info
  - dotnet restore

script:
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK tests/NSubstitute.Acceptance.Specs/NSubstitute.Acceptance.Specs.csproj
